defmodule Prettycore.ClientIntelligence.CiEvent do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  # No autogenerated timestamps — inserted_at is manual (:utc_datetime)
  @timestamps_opts [type: :utc_datetime]

  schema "ci_events" do
    field :client_code, :string
    field :event_type, :string   # viewed | edited | exported
    field :metadata, :map, default: %{}
    field :inserted_at, :utc_datetime

    belongs_to :user, Prettycore.Auth.AuthUser
  end

  @valid_types ~w(viewed edited exported created filtered)

  def changeset(event, attrs) do
    event
    |> cast(attrs, [:client_code, :user_id, :event_type, :metadata, :inserted_at])
    |> validate_required([:client_code, :event_type, :inserted_at])
    |> validate_inclusion(:event_type, @valid_types)
  end
end
